name: Github Workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: "What's your name?"

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello Logger!" > $GITHUB_STEP_SUMMARY
