name: Github Workflows

on:
  workflow_dispatch:
    inputs:
      Link:
        description: "Download Link"
        required: true
        type: string

jobs:
  fileDownloader:
    runs-on: ubuntu-latest
    steps:


      - name: Download Link
        run: echo "curl ${{ github.event.inputs.name }}" > $GITHUB_STEP_SUMMARY
      
      - name: curl Check
        run: curl -v > $GITHUB_STEP_SUMMARY
